### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by 471448446** [jkwiecien/Switcher#1]
anything for eclipse?

**Comment by jkwiecien** [comment]
sorry, not in plans.

**Comment by 471448446** [comment]
what’s  wrong?


来自 魅族 MX

-------- 原始邮件 --------
发件人：Jacek <notifications@github.com>
时间：周一 8月17日 22:07
收件人：jkwiecien/Switcher <Switcher@noreply.github.com>
抄送：471448446 <471448446@qq.com>
主题：Re: [Switcher] hello (#1)

**Comment by 471448446** [comment]
what’s wrong


来自 魅族 MX

-------- 原始邮件 --------
发件人：Jacek <notifications@github.com>
时间：周一 8月17日 22:07
收件人：jkwiecien/Switcher <Switcher@noreply.github.com>
抄送：471448446 <471448446@qq.com>
主题：Re: [Switcher] hello (#1)

**Comment by 471448446** [comment]
thinks，


来自 魅族 MX

-------- 原始邮件 --------
发件人：471448446 <471448446@qq.com>
时间：周一 8月17日 22:23
收件人：jkwiecien/Switcher <reply@reply.github.com>
抄送：jkwiecien/Switcher <Switcher@noreply.github.com>
主题：Re: [Switcher] hello (#1)

>what’s  wrong?来自 魅族 MX
