### ISSUE TITLE
Tag 2.0.0 is wrong and points to 1.1.4

### ISSUE THREAD

**Issue by tukak** [jkwiecien/Switcher#3]
Hello,
I believe tag 2.0.0 is wrong and points to 1.1.4. This makes jitpack serve 1.1.4 as 2.0.0.
See versionName in https://github.com/jkwiecien/Switcher/blob/2.0.0/build.gradle for example

**Comment by tukak** [comment]
As a workaround, using `compile 'com.github.jkwiecien:Switcher:fae99df'` downloads 2.0.0

**Comment by jkwiecien** [comment]
Thanks, fixing that

**Comment by tukak** [comment]
Thanks
