### ISSUE TITLE
Version 2.0.5 is too big - includes jni

### ISSUE THREAD

**Issue by tukak** [jkwiecien/Switcher#5]
Hi,
size of version 2.0.5 is 7 MB (version 2.0.1 is 11,5 KB)
Main difference is the jni folder, that is 6,96 MB.
Probably caused 1.5.0 gradle plugin

**Comment by tukak** [comment]
2.0.3 and 2.0.4 are also fine

**Comment by jkwiecien** [comment]
Hmm... any idea how to fix that without downgrading the gradle?

**Comment by tukak** [comment]
With gradle plugin 1.3.1 or without renderscript (removing the BlurUtils, which are not used anywhere) the jni is not included.
I would go with removing or rewriting the BlurUtils

**Comment by jkwiecien** [comment]
Try 2.0.6

**Comment by tukak** [comment]
It is fine in 2.0.6
Thank you
